# Generated by Django 5.2.17 on 2026-08-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('company', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('service', models.CharField(choices=[('software', 'Software Development'), ('web', 'Web Development'), ('mobile', 'Mobile App Development'), ('uiux', 'UI/UX Design'), ('ai', 'AI & Intelligent Systems'), ('automation', 'Business Automation'), ('other', 'Other')], max_length=50)),
                ('budget', models.CharField(blank=True, choices=[('below-100k', 'Below ₦100,000'), ('100k-300k', '₦100,000 – ₦300,000'), ('300k-500k', '₦300,000 – ₦500,000'), ('500k-1m', '₦500,000 – ₦1,000,000'), ('above-1m', 'Above ₦1,000,000'), ('discuss', "Let's Discuss")], max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
