# Generated by Django 5.2.17 on 2026-08-21 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contactmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
