# Generated by Django 5.2.17 on 2026-08-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinquiry',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactinquiry',
            name='reply',
            field=models.TextField(blank=True),
        ),
    ]
