# Generated by Django 5.2.17 on 2026-08-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contactinquiry_replied_at_contactinquiry_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinquiry',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('in_progress', 'In Progress'), ('replied', 'Replied'), ('closed', 'Closed')], default='new', max_length=20),
        ),
    ]
