# Generated by Django 5.2.17 on 2026-08-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contactinquiry_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinquiry',
            name='is_read',
        ),
        migrations.AddField(
            model_name='contactinquiry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
